/** Declaration file generated by dts-gen */

export const flash_key: string;

export const key: string;

export function install(Vue: any, options: any): any;

export function setAll(all: any): void;

